#! /usr/bin/env bash

# Shows the output of every command
set +x

activateHM() {
  #rm ~/.config/orage/oragerc.bak
  rm -rf ~/.config/secrets
  HOME_MANAGER_BACKUP_EXT=bak result/activate
  hm-changes-report
}

rebuild_home_edp() {
  nix build .#homeConfigurations.bismuth-edp.activationPackage --show-trace
  activateHM
}

rebuild_home_hdmi() {
  nix build .#homeConfigurations.bismuth-hdmi.activationPackage
  activateHM
}

rebuild_system() {
  #nix build .#nixosConfigurations.intelTower.config.system.build.toplevel
  #sudo result/bin/switch-to-configuration switch
  sudo nixos-rebuild switch --flake .#intelTower --impure
}

rebuild_intelTower() {
  sudo nixos-rebuild switch --flake .#intelTower --impure 
  nix build .#homeConfigurations.bismuth-edp.activationPackage
  activateHM 
}

rebuild_intelTower_withUpdate() {
  nix flake update 
  export NIXPKGS_ALLOW_BROKEN=1
  sudo nixos-rebuild switch --flake .#intelTower --impure --show-trace
  nix build .#homeConfigurations.bismuth-edp.activationPackage --impure --show-trace
  activateHM 
}

# was necessary to purge substitutes caches 
rebuild_scratchBuild() {
  nix flake update 
  sudo nixos-rebuild switch --flake .#intelTower --impure --option build-use-substitutes false --show-trace
  nix build .#homeConfigurations.bismuth-edp.activationPackage --option build-use-substitutes false --show-trace
  activateHM
}

rebuild_intelNUC() {
  nix flake update
  sudo nixos-rebuild switch --flake .#intelNUC --impure
  nix build .#homeConfigurations.bismuth-edp.activationPackage --show-trace
  activateHM
}

rebuild_vm() {
  sudo nixos-rebuild build-vm --flake .#intelTower --impure
}

restart_X() {
  echo "⚠️ Restarting X11 (requires authentication) ⚠️"
  systemctl restart display-manager
}

case $1 in
  "edp")
    rebuild_home_edp;;
  "hdmi")
    rebuild_home_hdmi;;
  "restart-x")
    restart_X;;
  "update-fish")
    fish -c fish_update_completions;;
  "system")
    rebuild_system;;  
  "intelTower")
    rebuild_intelTower;;
  "intelTowerNew")
    rebuild_intelTower_withUpdate;;
  "intelNUC")
    rebuild_intelNUC;;
  "scratchBuild")
    rebuild_scratchBuild;;
  "vm")
    rebuild_vm;;
  *)
    echo "expected 'edp', 'hdmi', 'restart-x', 'update-fish', 'system', 'intelTower' , 'intelTowerNew' , 'intelNUC' , 'scratchBuild', or 'vm'";;
esac
