{ pkgs, inputs, ... }:

{
 cardanoPackages = with inputs.cardano-node.packages.x86_64-linux; [
    #all-profiles-json
    
    #alonzo-purple/node
    #alonzo-purple/submit-api
    bech32
    #benchmarks/cardano-tracer/cardano-tracer-bench
    #benchmarks/trace-dispatcher/trace-dispatcher-bench
    #benchmarks/tx-generator/tx-generator-bench
    cabalProjectRegenerate
    cardano-cli
    cardano-node
    cardano-node-chairman
    cardano-ping
    cardano-submit-api
    cardano-testnet
    cardano-topology
    cardano-tracer
    chain-sync-client-with-ledger-state
    checkCabalProject
    #checks/cardano-api/cardano-api-test
    #checks/cardano-cli/cardano-cli-golden
    #checks/cardano-cli/cardano-cli-test
    #checks/cardano-node-chairman/chairman-tests
    #checks/cardano-node/cardano-node-test
    #checks/cardano-submit-api/unit
    #checks/cardano-testnet/cardano-testnet-tests
    #checks/cardano-tracer/cardano-tracer-test
    #checks/hlint
    #checks/locli/test-locli
    #checks/nixosTests/cardanoNodeEdge
    #checks/trace-dispatcher/trace-dispatcher-test
    #checks/trace-forward/test
    #checks/trace-resources/trace-resources-test
    #checks/tx-generator/tx-generator-test
    db-analyser
    db-converter
    db-synthesizer
    #demo-acceptor
    #demo-forwarder
    #dockerImage/node
    #dockerImage/node/load
    #dockerImage/submit-api
    #dockerImage/submit-api/load
    #dockerImages/push
    ledger-state
    locli
    mainnet/node
    mainnet/submit-api
    marlowe-pioneers/node
    marlowe-pioneers/submit-api
    p2p/node
    p2p/submit-api
    plutus-example
    preprod/node
    #preprod/submit-api
    #preview/node
    #preview/submit-api
    scan-blocks
    scan-blocks-pipelined
    #shelley_qa/node
    #shelley_qa/submit-api
    #sre/node
    #sre/submit-api
    #staging/node
    #staging/submit-api
    #stake-credential-history
    #testnet/node
    #testnet/submit-api
    #tests/cardano-api/cardano-api-test
    #tests/cardano-cli/cardano-cli-golden
    #tests/cardano-cli/cardano-cli-test
    #tests/cardano-node-chairman/chairman-tests
    #tests/cardano-node/cardano-node-test
    #tests/cardano-submit-api/unit
    #tests/cardano-testnet/cardano-testnet-tests
    #tests/cardano-tracer/cardano-tracer-test
    #tests/locli/test-locli
    #tests/trace-dispatcher/trace-dispatcher-test
    #tests/trace-forward/test
    #tests/trace-resources/trace-resources-test
    #tests/tx-generator/tx-generator-test
    #trace-dispatcher-examples
    tx-generator
    #vasil-dev/node
    #vasil-dev/submit-api
  ];
}